apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-hwtd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-hwtd
    app.kubernetes.io/part-of: test-annotations-app-ieau
  name: test-annotations-hwtd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-hwtd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-hwtd
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-ijxq-tenant/test-annotations-app-ieau/test-annotations-hwtd@sha256:3e32d5e046057cac4b88fd31992e7c5f722f256b7913bf8c0dfcb4c0c5e28ee1
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
